# Generated by Django 3.1.1 on 2020-09-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_album', models.TextField()),
                ('artista', models.CharField(max_length=100)),
                ('genero', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
