# Generated by Django 3.1.1 on 2020-09-17 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuns',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albuns',
            name='artista',
            field=models.CharField(max_length=200, verbose_name='Artista.'),
        ),
        migrations.AlterField(
            model_name='albuns',
            name='genero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='albuns',
            name='titulo_album',
            field=models.CharField(max_length=200, verbose_name='Álbum.'),
        ),
    ]
